name: catapush_flutter_sdk_example
description: Demonstrates how to use the catapush_flutter_sdk plugin.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  catapush_flutter_sdk:
    path: ../

  equatable: ^2.0.0
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  mime: ^1.0.5
  image_picker: ^1.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true