name: catapush_flutter_sdk_example
description: Demonstrates how to use the catapush_flutter_sdk plugin.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  catapush_flutter_sdk:
    # When depending on this package from a real application you should use:
    #   catapush_flutter_sdk: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.5
  equatable: ^2.0.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  mime: ^1.0.2
  image_picker: ^1.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true