name: catapush_flutter_sdk
description: Official Catapush plugin for Flutter, supports Android and iOS platforms
version: 1.5.0
homepage: https://www.catapush.com/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.4
  intl: ^0.17.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.catapush.flutter.sdk
        pluginClass: CatapushFlutterSdkPlugin
      ios:
        pluginClass: CatapushFlutterSdkPlugin
