name: catapush_flutter_sdk
description: Official Catapush plugin for Flutter, supports Android and iOS platforms
version: 1.7.0
homepage: https://www.catapush.com/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^2.0.0
  intl: ^0.19.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.catapush.flutter.sdk
        pluginClass: CatapushFlutterSdkPlugin
      ios:
        pluginClass: CatapushFlutterSdkPlugin
