name: catapush_flutter_sdk
description: Official Catapush plugin for Flutter, supports Android and iOS platforms
version: 1.8.0
homepage: https://www.catapush.com/

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^2.0.0
  intl: ^0.20.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.catapush.flutter.sdk
        pluginClass: CatapushFlutterSdkPlugin
      ios:
        pluginClass: CatapushFlutterSdkPlugin
